# BERT Tokenizer Configuration
tokenizers:
  bert:
    model_name: "bert-base-uncased"
    special_tokens:
      bos_token: "[DEC]"
    max_length: 512
    padding: true
    truncation: true
    return_tensors: "pt"

# Image Processor Configuration
image_processors:
  blip2:
    type: "blip2"
    image_size: 224
    normalize_mean: [0.48145466, 0.4578275, 0.40821073]
    normalize_std: [0.26862954, 0.26130258, 0.27577711]
    enable_patch_embed: true
    patch_size: 16
    in_channels: 3
    embed_dim: 768
    enable_vision_transformer: true
    drop_path_rate: 0.4
    use_checkpoint: false
    precision: "fp16"
  
  clip:
    type: "clip"
    image_size: 224
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]
    enable_patch_embed: false
    patch_size: 16
    in_channels: 3
    embed_dim: 512

